move('#title')
  .ease("out")
  .set('opacity', 1)
  .set("right", "-1.5%")
  .duration("3s")
.end();

move("#what")
  .ease("out")
  .set('opacity', 1)
  .set("right", "-4.5%")
  .delay("1s")
  .duration("3s")
.end()

move("#who")
  .ease("out")
  .set('opacity', 1)
  .set("right", "-4.5%")
  .delay("1.5s")
  .duration("3s")
.end()

move("#made")
  .ease("out")
  .set('opacity', 1)
  .set("right", "-4.5%")
  .delay("2s")
  .duration("3s")
.end()
